version: "3.9"
services:
  jaws:
    image: "ghcr.io/exlted/just-another-websocket-server"
    depends_on:
      - "rabbit-mq"
    environment:
    # Uncomment and define to provide your custom chat UI to this container
    #volumes:
    #  - /customization:/public/cust
    ports:
      - 8080:8080
    restart: on-failure
